services:
  api:
    container_name: api
    depends_on:
      - db
    build:
      context: ./backend
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./backend:/api
    env_file:
      - ./backend/.env

  db:
    container_name: db
    image: postgres:17
    env_file:
      - ./backend/.env
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
